# Generated by Django 5.0.4 on 2024-05-28 22:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0001_initial"),
        ("orgsite", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TrakOrg",
            new_name="Org",
        ),
        migrations.RenameModel(
            old_name="TrakOrgAccess",
            new_name="OrgAccess",
        ),
    ]
