# Generated by Django 5.0.7 on 2024-08-01 19:39

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_alter_orggroupobjectpermission_content_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
