# Generated by Django 5.0.7 on 2024-08-02 14:27

import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_alter_orggroupobjectpermission_content_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
        migrations.AddIndex(
            model_name='org',
            index=models.Index(fields=['slug'], name='org_slug_idx'),
        ),
    ]
