# Generated by Django 4.2.10 on 2024-02-17 19:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('rcrasite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrakSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'site aliases must be longer than 2 characters')], verbose_name='site alias')),
                ('last_rcrainfo_manifest_sync', models.DateTimeField(blank=True, null=True, verbose_name='last RCRAInfo manifest sync date')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.trakorg')),
                ('rcra_site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rcrasite.rcrasite', verbose_name='rcra_site')),
            ],
            options={
                'verbose_name': 'Haztrak Site',
                'verbose_name_plural': 'Haztrak Sites',
                'ordering': ['rcra_site__epa_id'],
            },
        ),
        migrations.CreateModel(
            name='TrakSiteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emanifest', models.CharField(choices=[('viewer', 'view'), ('editor', 'edit'), ('signer', 'sign')], default='view', max_length=6)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.traksite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'New Site Permission',
                'verbose_name_plural': 'New Site Permissions',
                'ordering': ['user'],
            },
        ),
    ]
