# Generated by Django 4.0.4 on 2022-04-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.IntegerField(blank=True, null=True)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(blank=True, default=None, max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=32)),
                ('state_name', models.CharField(choices=[('AK', 'Alaska'), ('AL', 'Alabama'), ('AP', 'Armed Forces Pacific'), ('AR', 'Arkansas'), ('AZ', 'Arizona'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'Washington DC'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('ME', 'Maine'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MS', 'Mississippi'), ('MT', 'Montana'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NE', 'Nebraska'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('NY', 'New York'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('VT', 'Vermont'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming'), ('XA', 'REGION 01 PURVIEW'), ('XB', 'REGION 02 PURVIEW'), ('XC', 'REGION 03 PURVIEW'), ('XD', 'REGION 04 PURVIEW'), ('XE', 'REGION 05 PURVIEW'), ('XF', 'REGION 06 PURVIEW'), ('XG', 'REGION 07 PURVIEW'), ('XH', 'REGION 08 PURVIEW'), ('XI', 'REGION 09 PURVIEW'), ('XJ', 'REGION 10 PURVIEW')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_first_name', models.CharField(max_length=200)),
                ('signer_last_name', models.CharField(max_length=200)),
                ('signer_user_id', models.CharField(max_length=200)),
                ('signature_date', models.DateTimeField(verbose_name='signature_date')),
            ],
        ),
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epaSiteId', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=200)),
                ('modified', models.BooleanField()),
                ('registered', models.BooleanField()),
                ('mailingAddress', models.JSONField()),
                ('siteAddress', models.JSONField()),
                ('contact', models.JSONField()),
                ('emergencyPhone', models.JSONField(null=True)),
                ('electronicSignaturesInfo', models.JSONField(null=True)),
                ('gisPrimary', models.BooleanField()),
                ('canEsign', models.BooleanField()),
                ('limitedEsign', models.BooleanField()),
                ('hasRegisteredEmanifestUser', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifestTrackingNumber', models.CharField(max_length=15)),
                ('createdDate', models.DateTimeField(null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('notAssigned', 'Not Assigned'), ('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('InTransit', 'In Transit'), ('ReadyForSignature', 'Ready for Signature'), ('Signed', 'Signed'), ('Corrected', 'Corrected'), ('UnderCorrection', 'Under Correction'), ('MtnValidationFailed', 'MTN Validation Failed')], default='notAssigned', max_length=25)),
                ('discrepancy', models.BooleanField(default=False)),
                ('submissionType', models.CharField(choices=[('FullElectronic', 'Full Electronic'), ('DataImage5Copy', 'Data + Image'), ('Hybrid', 'Hybrid'), ('Image', 'Image')], default='FullElectronic', max_length=25)),
                ('originType', models.CharField(choices=[('Web', 'Web'), ('Service', 'Service'), ('Mail', 'Mail')], default='Service', max_length=25)),
                ('shippedDate', models.DateTimeField(null=True, verbose_name='Shipped date')),
                ('receivedDate', models.DateTimeField(null=True, verbose_name='Received date')),
                ('transporters', models.JSONField()),
                ('broker', models.JSONField(null=True)),
                ('wastes', models.JSONField()),
                ('additionalInfo', models.JSONField(null=True)),
                ('printedDocument', models.JSONField(null=True)),
                ('rejection', models.BooleanField(null=True)),
                ('residue', models.BooleanField(null=True)),
                ('residueNewManifestTrackingNumbers', models.JSONField()),
                ('importFlag', models.BooleanField(null=True, verbose_name='import')),
                ('containsPreviousRejectOrResidue', models.BooleanField(null=True)),
                ('formDocument', models.JSONField(null=True)),
                ('newResidueManifestTrackingNumbers', models.JSONField(null=True)),
                ('rejectionInfo', models.JSONField(null=True)),
                ('importInfo', models.JSONField(null=True)),
                ('correctionInfo', models.JSONField(null=True)),
                ('ppcInfo', models.JSONField(null=True)),
                ('transferRequested', models.BooleanField(null=True)),
                ('transferStatus', models.CharField(max_length=200, null=True)),
                ('originalSubmissionType', models.CharField(choices=[('FullElectronic', 'Full Electronic'), ('DataImage5Copy', 'Data + Image'), ('Hybrid', 'Hybrid'), ('Image', 'Image')], max_length=25, null=True)),
                ('potentialShipDate', models.DateTimeField(null=True, verbose_name='Potential Ship Date')),
                ('reTransferCount', models.IntegerField(null=True)),
                ('nextTransferTime', models.DateTimeField(null=True, verbose_name='Next Transfer Time')),
                ('locked', models.BooleanField(null=True)),
                ('lockReason', models.CharField(max_length=25, null=True)),
                ('certifiedDate', models.DateTimeField(null=True, verbose_name='Certified date')),
                ('certifiedBy', models.JSONField(null=True)),
                ('designatedFacility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Designated_Facility', to='trak.handler')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Generator', to='trak.handler')),
            ],
        ),
        migrations.CreateModel(
            name='EpaSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epa_id', models.CharField(max_length=32)),
                ('epa_name', models.CharField(max_length=200, null=True)),
                ('modified', models.BooleanField(null=True)),
                ('has_site_id', models.BooleanField(null=True)),
                ('registered', models.BooleanField(null=True)),
                ('gis_primary', models.BooleanField(default=False)),
                ('can_esign', models.BooleanField(default=False)),
                ('limited_esign', models.BooleanField(default=True)),
                ('has_emanifest_user', models.BooleanField(default=False)),
                ('site_type', models.CharField(choices=[('GEN', 'Generator'), ('TRAN', 'Transporter'), ('TSD', 'Receiving Facility')], default='GEN', max_length=32)),
                ('federal_generator_status', models.CharField(choices=[('SQG', 'SQG'), ('LQG', 'LQG'), ('VSQG', 'VSQG')], default=None, max_length=32, null=True)),
                ('mailing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_address', to='trak.address')),
                ('site_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_address', to='trak.address')),
            ],
        ),
    ]
