# Generated by Django 4.0.4 on 2022-04-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_first_name', models.CharField(max_length=200)),
                ('signer_last_name', models.CharField(max_length=200)),
                ('signer_user_id', models.CharField(max_length=200)),
                ('signature_date', models.DateTimeField(verbose_name='signature_date')),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='update date')),
                ('manifest_tracking_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('notAssigned', 'Not Assigned'), ('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('InTransit', 'In Transit'), ('ReadyForSignature', 'Ready for Signature'), ('Signed', 'Signed'), ('Corrected', 'Corrected'), ('UnderCorrection', 'Under Correction'), ('MtnValidationFailed', 'MTN Validation Failed')], default='notAssigned', max_length=25)),
                ('submission_type', models.CharField(choices=[('FullElectronic', 'Full Electronic'), ('DataImage5Copy', 'Data + Image'), ('Hybrid', 'Hybrid'), ('Image', 'Image')], default='FullElectronic', max_length=25)),
                ('origin_type', models.CharField(choices=[('Web', 'Web'), ('Service', 'Service'), ('Mail', 'Mail')], default='Service', max_length=25)),
                ('shipped_date', models.DateTimeField(null=True, verbose_name='shipped date')),
                ('potential_ship_date', models.CharField(max_length=15, null=True)),
                ('received_date', models.DateTimeField(null=True, verbose_name='received date')),
                ('certified_date', models.DateTimeField(null=True, verbose_name='certified date')),
                ('transporter', models.JSONField()),
                ('generator_id', models.CharField(max_length=25)),
                ('generator_info', models.JSONField()),
                ('tsd_id', models.CharField(max_length=25)),
                ('tsd_info', models.JSONField()),
                ('rejection', models.BooleanField(default=False)),
                ('residue', models.BooleanField(default=False)),
                ('import_waste', models.BooleanField(default=False)),
                ('contains_rejected_residue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifestTrackingNumber', models.CharField(max_length=15)),
                ('createdDate', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('notAssigned', 'Not Assigned'), ('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('InTransit', 'In Transit'), ('ReadyForSignature', 'Ready for Signature'), ('Signed', 'Signed'), ('Corrected', 'Corrected'), ('UnderCorrection', 'Under Correction'), ('MtnValidationFailed', 'MTN Validation Failed')], default='notAssigned', max_length=25)),
            ],
        ),
    ]
