# Generated by Django 4.0.4 on 2022-05-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='discrepancy',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='import_flag',
            field=models.BooleanField(blank=True, default=False, verbose_name='Import'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='rejection',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='residue',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='residue_new_mtn',
            field=models.JSONField(blank=True, default=[], verbose_name='Residue new MTN'),
        ),
    ]
