# Generated by Django 4.0.3 on 2022-04-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_first_name', models.CharField(max_length=200)),
                ('signer_last_name', models.CharField(max_length=200)),
                ('signer_user_id', models.CharField(max_length=200)),
                ('signature_date', models.DateTimeField(verbose_name='signature_date')),
            ],
        ),
        migrations.AddField(
            model_name='manifest',
            name='transporter',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
