# Generated by Django 4.0.4 on 2022-04-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
