# Generated by Django 4.0.4 on 2022-04-15 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestsimple',
            name='createdDate',
        ),
    ]
