# Generated by Django 4.0.4 on 2022-04-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0002_alter_address_address1_alter_address_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='certified_by',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='certified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='created_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='discrepancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='form_document',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generator', to='trak.handler'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='origin_type',
            field=models.CharField(choices=[('Web', 'Web'), ('Service', 'Service'), ('Mail', 'Mail')], default='Service', max_length=25),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='printed_document',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='rejection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='residue',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='signature_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='status',
            field=models.CharField(choices=[('notAssigned', 'Not Assigned'), ('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('InTransit', 'In Transit'), ('ReadyForSignature', 'Ready for Signature'), ('Signed', 'Signed'), ('Corrected', 'Corrected'), ('UnderCorrection', 'Under Correction'), ('MtnValidationFailed', 'MTN Validation Failed')], default='notAssigned', max_length=25),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='submission_type',
            field=models.CharField(choices=[('FullElectronic', 'Full Electronic'), ('DataImage5Copy', 'Data + Image'), ('Hybrid', 'Hybrid'), ('Image', 'Image')], default='FullElectronic', max_length=25),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='transporters',
            field=models.JSONField(),
        ),
    ]
