# Generated by Django 4.0.4 on 2022-04-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0002_remove_manifestsimple_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestsimple',
            name='createdDate',
            field=models.DateTimeField(null=True),
        ),
    ]
