# Generated by Django 4.0.4 on 2022-04-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0002_electronicsignature_manifest_transporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='generator_info',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifest',
            name='tsd_info',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
