# Generated by Django 4.0.4 on 2022-04-27 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0002_alter_address_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='additionalInfo',
            field=models.JSONField(blank=True, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='broker',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='certifiedBy',
            field=models.JSONField(blank=True, null=True, verbose_name='Certified By'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='certifiedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Certified date'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='containsPreviousRejectOrResidue',
            field=models.BooleanField(null=True, verbose_name='Contains previous rejection or residue'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='correctionInfo',
            field=models.JSONField(blank=True, null=True, verbose_name='Correction Info'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='createdDate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='designatedFacility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designated_facility', to='trak.handler', verbose_name='Designated facility'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='discrepancy',
            field=models.BooleanField(default=False, verbose_name='Discrepancy'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='formDocument',
            field=models.JSONField(blank=True, null=True, verbose_name='Form Document'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generator', to='trak.handler', verbose_name='Generator'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='importFlag',
            field=models.BooleanField(blank=True, null=True, verbose_name='Import'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='importInfo',
            field=models.JSONField(blank=True, null=True, verbose_name='Import Information'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='lockReason',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Lock Reason'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='locked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='manifestTrackingNumber',
            field=models.CharField(max_length=15, verbose_name='Manifest Tracking Number'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='newResidueManifestTrackingNumbers',
            field=models.JSONField(null=True, verbose_name='New Residue MTN'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='nextTransferTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next Transfer Time'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='originType',
            field=models.CharField(choices=[('Web', 'Web'), ('Service', 'Service'), ('Mail', 'Mail')], default='Service', max_length=25, verbose_name='Origin Type'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='originalSubmissionType',
            field=models.CharField(choices=[('FullElectronic', 'Full Electronic'), ('DataImage5Copy', 'Data + Image'), ('Hybrid', 'Hybrid'), ('Image', 'Image')], max_length=25, null=True, verbose_name='Original Submission Type'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='potentialShipDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Potential Ship Date'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='ppcInfo',
            field=models.JSONField(blank=True, null=True, verbose_name='PPC Info'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='printedDocument',
            field=models.JSONField(blank=True, null=True, verbose_name='Printed Document'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='reTransferCount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Transfer Count'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='receivedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Received date'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='rejection',
            field=models.BooleanField(blank=True, null=True, verbose_name='Rejection'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='rejectionInfo',
            field=models.JSONField(blank=True, null=True, verbose_name='Rejection Information'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='residue',
            field=models.BooleanField(blank=True, null=True, verbose_name='Residue'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='shippedDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Shipped date'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='status',
            field=models.CharField(choices=[('notAssigned', 'Not Assigned'), ('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('InTransit', 'In Transit'), ('ReadyForSignature', 'Ready for Signature'), ('Signed', 'Signed'), ('Corrected', 'Corrected'), ('UnderCorrection', 'Under Correction'), ('MtnValidationFailed', 'MTN Validation Failed')], default='notAssigned', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='submissionType',
            field=models.CharField(choices=[('FullElectronic', 'Full Electronic'), ('DataImage5Copy', 'Data + Image'), ('Hybrid', 'Hybrid'), ('Image', 'Image')], default='FullElectronic', max_length=25, verbose_name='Submission Type'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='transferRequested',
            field=models.BooleanField(blank=True, null=True, verbose_name='Transfer Requested'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='transferStatus',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Transfer Status'),
        ),
    ]
