# Generated by Django 4.0.4 on 2022-05-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0002_alter_manifest_discrepancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='residue_new_mtn',
            field=models.JSONField(blank=True, default=list, verbose_name='Residue new MTN'),
        ),
    ]
