# Generated by Django 4.0.4 on 2022-04-29 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0003_alter_manifest_certified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handler',
            name='emergency_phone',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handler',
            name='mailing_address',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='handler',
            name='modified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handler',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='handler',
            name='registered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handler',
            name='site_address',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='correction_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='locked_reason',
            field=models.CharField(blank=True, choices=[('AsyncSign', 'Asynchronous signature'), ('EpaChangeBiller', 'EPA change biller'), ('EpaCorrection', 'EPA corrections')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='transfer_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='transfer_requested',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='transfer_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='epa_site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trak.handler', verbose_name='Handler'),
        ),
    ]
