# Generated by Django 4.0.4 on 2022-04-15 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0003_manifestsimple_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestsimple',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 16, 49, 46, 237216), null=True),
        ),
    ]
