# Generated by Django 4.0.4 on 2022-04-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0003_alter_manifest_additionalinfo_alter_manifest_broker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='residueNewManifestTrackingNumbers',
            field=models.JSONField(verbose_name='Residue MTN'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='transporters',
            field=models.JSONField(verbose_name='Transporters'),
        ),
    ]
