# Generated by Django 4.0.4 on 2022-05-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0004_rename_order_transporter_transporter_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transporter',
            old_name='transporter_order',
            new_name='order',
        ),
    ]
