# Generated by Django 4.0.4 on 2022-04-28 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0004_alter_manifest_residuenewmanifesttrackingnumbers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='manifestTrackingNumber',
            new_name='mtn',
        ),
    ]
