# Generated by Django 4.0.4 on 2022-05-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0004_remove_address_state_name_remove_address_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.JSONField(choices=[('VA', 'Virginia')]),
        ),
    ]
