# Generated by Django 4.0.4 on 2022-05-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0005_rename_transporter_order_transporter_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter',
            name='my_field',
        ),
        migrations.AlterField(
            model_name='transporter',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
