# Generated by Django 4.0.4 on 2022-04-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0005_rename_manifesttrackingnumber_manifest_mtn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='containsPreviousRejectOrResidue',
            field=models.BooleanField(blank=True, null=True, verbose_name='Contains previous rejection or residue'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='newResidueManifestTrackingNumbers',
            field=models.JSONField(blank=True, null=True, verbose_name='New Residue MTN'),
        ),
    ]
