# Generated by Django 4.0.4 on 2022-06-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0005_alter_address_country_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
