# Generated by Django 4.0.4 on 2022-05-24 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0006_remove_transporter_my_field_alter_transporter_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='handler',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='trak.handler'),
            preserve_default=False,
        ),
    ]
