# Generated by Django 4.0.4 on 2022-04-18 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0006_manifestsimple_origin_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestsimple',
            name='origin_type',
        ),
        migrations.RemoveField(
            model_name='manifestsimple',
            name='submission_type',
        ),
        migrations.AlterField(
            model_name='manifestsimple',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 10, 16, 1, 626352), null=True),
        ),
    ]
