# Generated by Django 4.0.4 on 2022-04-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0006_alter_manifest_containspreviousrejectorresidue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='createdDate',
            new_name='created_date',
        ),
    ]
