# Generated by Django 4.0.4 on 2022-05-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0007_remove_address_state_name_remove_address_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.JSONField(blank=True, choices=[('US', 'United States')], max_length=32, null=True),
        ),
    ]
