# Generated by Django 4.0.4 on 2022-05-24 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0007_transporter_handler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter',
            name='handler',
        ),
        migrations.RemoveField(
            model_name='transporter',
            name='id',
        ),
        migrations.AddField(
            model_name='transporter',
            name='handler_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trak.handler'),
            preserve_default=False,
        ),
    ]
