# Generated by Django 4.0.4 on 2022-04-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0007_rename_createddate_manifest_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='updatedDate',
            new_name='update_date',
        ),
    ]
