# Generated by Django 4.0.4 on 2022-05-24 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0008_remove_transporter_handler_remove_transporter_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='transporters',
        ),
    ]
