# Generated by Django 4.0.4 on 2022-06-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0008_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, choices=[('US', 'United States'), ('MX', 'Mexico'), ('CA', 'Canada')], max_length=3, null=True),
        ),
    ]
