# Generated by Django 4.0.4 on 2022-04-18 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0008_manifestsimple_submissiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestsimple',
            name='originType',
            field=models.CharField(choices=[('Web', 'Web'), ('Service', 'Service'), ('Mail', 'Mail')], default='Service', max_length=25),
        ),
        migrations.AlterField(
            model_name='manifestsimple',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 10, 28, 39, 371471), null=True),
        ),
    ]
