# Generated by Django 4.0.4 on 2022-04-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0008_rename_updateddate_manifest_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='originType',
            new_name='origin_type',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='submissionType',
            new_name='submission_type',
        ),
    ]
