# Generated by Django 4.0.4 on 2022-04-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0009_rename_origintype_manifest_origin_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='receivedDate',
            new_name='received_date',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='shippedDate',
            new_name='shipped_date',
        ),
    ]
