# Generated by Django 4.0.4 on 2022-05-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0009_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='handler',
            name='mailing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_address', to='trak.address'),
        ),
    ]
