# Generated by Django 4.0.4 on 2022-05-24 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0009_remove_manifest_transporters'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='manifest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transporters', to='trak.manifest'),
            preserve_default=False,
        ),
    ]
