# Generated by Django 4.0.4 on 2022-04-18 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0009_manifestsimple_origintype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestsimple',
            name='shippedDate',
            field=models.DateTimeField(null=True, verbose_name='shipped date'),
        ),
        migrations.AlterField(
            model_name='manifestsimple',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 10, 44, 33, 552681), null=True),
        ),
    ]
