# Generated by Django 4.0.4 on 2022-04-18 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0010_manifestsimple_shippeddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestsimple',
            name='potentialShipDate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='manifestsimple',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 10, 47, 25, 135580), null=True),
        ),
    ]
