# Generated by Django 4.0.4 on 2022-04-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0011_rename_designatedfacility_manifest_tsd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='additionalInfo',
            new_name='additional_info',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='printedDocument',
            new_name='printed_document',
        ),
    ]
