# Generated by Django 4.0.4 on 2022-04-18 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0011_manifestsimple_potentialshipdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestsimple',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 10, 52, 14, 552169), null=True),
        ),
        migrations.AlterField(
            model_name='manifestsimple',
            name='potentialShipDate',
            field=models.DateTimeField(null=True, verbose_name='Potential Ship Date'),
        ),
    ]
