# Generated by Django 4.0.4 on 2022-04-18 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0012_alter_manifestsimple_createddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestsimple',
            name='certifiedDate',
            field=models.DateTimeField(null=True, verbose_name='Certified date'),
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='receivedDate',
            field=models.DateTimeField(null=True, verbose_name='Received date'),
        ),
        migrations.AlterField(
            model_name='manifestsimple',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 10, 53, 22, 251076), null=True),
        ),
        migrations.AlterField(
            model_name='manifestsimple',
            name='shippedDate',
            field=models.DateTimeField(null=True, verbose_name='Shipped date'),
        ),
    ]
