# Generated by Django 4.0.4 on 2022-04-18 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0013_manifestsimple_certifieddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestsimple',
            name='transporters',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestsimple',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 10, 57, 5, 497581), null=True),
        ),
    ]
