# Generated by Django 4.0.4 on 2022-04-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0013_rename_importflag_manifest_import_flag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='containsPreviousRejectOrResidue',
            new_name='contains_residue_or_rejection',
        ),
    ]
