# Generated by Django 4.0.4 on 2022-04-18 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0014_manifestsimple_transporters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestsimple',
            name='generatorID',
            field=models.CharField(default='id123', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestsimple',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 11, 41, 48, 12120), null=True),
        ),
    ]
