# Generated by Django 4.0.4 on 2022-05-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0014_alter_handler_site_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='site_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_address', to='trak.address'),
        ),
    ]
