# Generated by Django 4.0.4 on 2022-04-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0014_rename_containspreviousrejectorresidue_manifest_contains_residue_or_rejection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='formDocument',
            new_name='form_document',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='potentialShipDate',
            new_name='potential_ship_date',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='rejectionInfo',
            new_name='rejection_info',
        ),
        migrations.RemoveField(
            model_name='manifest',
            name='newResidueManifestTrackingNumbers',
        ),
        migrations.AlterField(
            model_name='manifest',
            name='residue_new_mtn',
            field=models.JSONField(blank=True, null=True, verbose_name='Residue new MTN'),
        ),
    ]
