# Generated by Django 4.0.4 on 2022-04-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0015_rename_formdocument_manifest_form_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='certifiedDate',
            new_name='certified_date',
        ),
        migrations.AddField(
            model_name='manifest',
            name='signature_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Signature status'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='potential_ship_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Potential ship date'),
        ),
    ]
