# Generated by Django 4.0.4 on 2022-04-18 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0016_remove_manifestsimple_generatorid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifestsimple',
            old_name='waste',
            new_name='wastes',
        ),
        migrations.AlterField(
            model_name='manifestsimple',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 11, 48, 30, 209827), null=True),
        ),
    ]
