# Generated by Django 4.0.4 on 2022-05-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0016_alter_handler_site_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handler',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='site_address',
        ),
        migrations.AddField(
            model_name='handler',
            name='mail_address1',
            field=models.CharField(default='address 1 text', max_length=50, verbose_name='Mailing address 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='mail_address2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Mailing address 2'),
        ),
        migrations.AddField(
            model_name='handler',
            name='mail_city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='handler',
            name='mail_country',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handler',
            name='mail_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handler',
            name='mail_street_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='handler',
            name='mail_zip',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='handler',
            name='site_address1',
            field=models.CharField(default='site address text', max_length=50, verbose_name='Site address 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='site_address2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Site address 2'),
        ),
        migrations.AddField(
            model_name='handler',
            name='site_city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='handler',
            name='site_country',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handler',
            name='site_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handler',
            name='site_street_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='handler',
            name='site_zip',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
