# Generated by Django 4.0.4 on 2022-05-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0017_remove_handler_mailing_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
