# Generated by Django 4.0.4 on 2022-04-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0017_rename_importinfo_manifest_import_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='ppcInfo',
        ),
        migrations.AddField(
            model_name='manifest',
            name='ppc_status',
            field=models.JSONField(blank=True, null=True, verbose_name='PPC info'),
        ),
    ]
