# Generated by Django 4.0.4 on 2022-04-18 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0017_rename_waste_manifestsimple_wastes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestsimple',
            name='additionalInfo',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='printedDocument',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='rejection',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='residue',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='manifestsimple',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 11, 55, 36, 925326), null=True),
        ),
    ]
