# Generated by Django 4.0.4 on 2022-04-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0018_remove_manifest_ppcinfo_manifest_ppc_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manifest',
            old_name='certifiedBy',
            new_name='certified_by',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='nextTransferTime',
            new_name='next_transfer_time',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='originalSubmissionType',
            new_name='original_sub_type',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='reTransferCount',
            new_name='transfer_count',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='transferRequested',
            new_name='transfer_requested',
        ),
        migrations.RenameField(
            model_name='manifest',
            old_name='transferStatus',
            new_name='transfer_status',
        ),
        migrations.RemoveField(
            model_name='manifest',
            name='lockReason',
        ),
        migrations.AddField(
            model_name='manifest',
            name='locked_reason',
            field=models.CharField(blank=True, choices=[('AsyncSign', 'Asynchronous signature'), ('EpaChangeBiller', 'EPA change biller'), ('EpaCorrection', 'EPA corrections')], max_length=25, null=True, verbose_name='Lock reason'),
        ),
    ]
