# Generated by Django 4.0.4 on 2022-04-18 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0018_manifestsimple_additionalinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestsimple',
            name='containsPreviousRejectOrResidue',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='formDocument',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='importFlag',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='manifestsimple',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 12, 43, 14, 661080), null=True),
        ),
    ]
