# Generated by Django 4.0.4 on 2022-04-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0019_rename_certifiedby_manifest_certified_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='handler',
            old_name='epaSiteId',
            new_name='epa_id',
        ),
    ]
