# Generated by Django 4.0.4 on 2022-05-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0019_alter_handler_mail_country_alter_handler_mail_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='transporters',
        ),
        migrations.AddField(
            model_name='manifest',
            name='transporters',
            field=models.ManyToManyField(to='trak.handler'),
        ),
    ]
