# Generated by Django 4.0.4 on 2022-05-11 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0020_remove_manifest_transporters_manifest_transporters'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot_hazardous', models.BooleanField(verbose_name='DOT hazardous')),
                ('dot_id', models.CharField(max_length=12, verbose_name='DOT ID number')),
                ('dot_printed_info', models.CharField(max_length=500, verbose_name='DOT printed information')),
                ('waste_description', models.CharField(blank=True, max_length=500, null=True)),
                ('container_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)], verbose_name='Number of containers')),
                ('container_type', models.CharField(choices=[('BA', 'Burlap, cloth, paper, or plastic bags'), ('DT', 'Dump truck'), ('CF', 'Fiber or plastic boxes, cartons, cases'), ('DW', 'Wooden drums, barrels, kegs'), ('CM', 'Metal boxes, cartons, cases (including roll offs)'), ('HG', 'Hopper or gondola cars'), ('CW', 'Wooden boxes, cartons, cases'), ('TC', 'Tank cars'), ('CY', 'Cylinders'), ('TP', 'Portable tanks'), ('DF', 'Fiberboard or plastic drums, barrels, kegs'), ('TT', 'Cargo tanks (tank trucks)'), ('DM', 'Metal drums, barrels, kegs')], max_length=2)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('uom', models.CharField(choices=[('P', 'Pounds'), ('T', 'Tons (2000 Pounds)'), ('K', 'Kilograms'), ('M', 'Metric Tons (1000 Kilograms)'), ('G', 'Gallons'), ('L', 'Liters'), ('Y', 'Cubic Yards'), ('N', 'Cubic Meters')], max_length=1, verbose_name='Unit of Measurement')),
            ],
        ),
    ]
