# Generated by Django 4.0.4 on 2022-04-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0020_rename_epasiteid_handler_epa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handler',
            name='canEsign',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='electronicSignaturesInfo',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='emergencyPhone',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='gisPrimary',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='hasRegisteredEmanifestUser',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='limitedEsign',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='mailingAddress',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='siteAddress',
        ),
        migrations.AddField(
            model_name='handler',
            name='can_esign',
            field=models.BooleanField(blank=True, null=True, verbose_name='Can electronically sign'),
        ),
        migrations.AddField(
            model_name='handler',
            name='electronic_signatures_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Electronic signature info'),
        ),
        migrations.AddField(
            model_name='handler',
            name='emergency_phone',
            field=models.JSONField(blank=True, null=True, verbose_name='Emergency phone'),
        ),
        migrations.AddField(
            model_name='handler',
            name='gis_primary',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='GIS primary'),
        ),
        migrations.AddField(
            model_name='handler',
            name='limited_esign',
            field=models.BooleanField(blank=True, null=True, verbose_name='Limited electronic signing ability'),
        ),
        migrations.AddField(
            model_name='handler',
            name='mailing_address',
            field=models.JSONField(default={}, verbose_name='Mailing address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='registered_emanifest_user',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Has Registered e-Manifest user'),
        ),
        migrations.AddField(
            model_name='handler',
            name='site_address',
            field=models.JSONField(default={}, verbose_name='Site address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handler',
            name='contact',
            field=models.JSONField(verbose_name='Contact information'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='epa_id',
            field=models.CharField(max_length=25, verbose_name='EPA Id number'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='modified',
            field=models.BooleanField(verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='registered',
            field=models.BooleanField(verbose_name='Registered'),
        ),
    ]
