# Generated by Django 4.0.4 on 2022-04-18 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0021_alter_manifestsimple_createddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestsimple',
            name='certifiedBy',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='correctionInfo',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='importInfo',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='lockReason',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='locked',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='newResidueManifestTrackingNumbers',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='nextTransferTime',
            field=models.DateTimeField(null=True, verbose_name='Next Transfer Time'),
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='originalSubmissionType',
            field=models.CharField(choices=[('FullElectronic', 'Full Electronic'), ('DataImage5Copy', 'Data + Image'), ('Hybrid', 'Hybrid'), ('Image', 'Image')], default={}, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='ppcInfo',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='reTransferCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='rejectionInfo',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='transferRequested',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='manifestsimple',
            name='transferStatus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='manifestsimple',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 12, 59, 56, 728421), null=True),
        ),
    ]
