# Generated by Django 4.0.4 on 2022-04-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0021_remove_handler_canesign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='modified',
            field=models.BooleanField(blank=True, null=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='registered',
            field=models.BooleanField(blank=True, null=True, verbose_name='Registered'),
        ),
    ]
