# Generated by Django 4.0.4 on 2022-05-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0021_wasteline'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteline',
            name='epa_waste',
            field=models.BooleanField(default=True, verbose_name='Is EPA waste?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasteline',
            name='line_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
