# Generated by Django 4.0.4 on 2022-05-18 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0022_wasteline_epa_waste_wasteline_line_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasteline',
            old_name='uom',
            new_name='quantity_uom',
        ),
        migrations.AddField(
            model_name='wasteline',
            name='br_info',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasteline',
            name='br_provided',
            field=models.BooleanField(default=False, verbose_name='BR info provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasteline',
            name='density',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999.99)]),
        ),
        migrations.AddField(
            model_name='wasteline',
            name='density_uom',
            field=models.CharField(blank=True, choices=[('1', 'lbs/gal'), ('2', 'sg')], max_length=5, null=True, verbose_name='Density units of Measurement'),
        ),
        migrations.AddField(
            model_name='wasteline',
            name='discrepancy_comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wasteline',
            name='discrepancy_residue_info',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasteline',
            name='federal_waste',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasteline',
            name='form_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='wasteline',
            name='hazardous_waste',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasteline',
            name='management_method',
            field=models.CharField(default={}, max_length=5, verbose_name='Management Method Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasteline',
            name='pcb',
            field=models.BooleanField(default=False, verbose_name='Contains PCBs?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasteline',
            name='pcb_info',
            field=models.JSONField(default={}, verbose_name='PCB information'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wasteline',
            name='quantity_discrepancy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasteline',
            name='residue',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasteline',
            name='residue_comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wasteline',
            name='source_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='wasteline',
            name='type_discrepancy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasteline',
            name='waste_minimization_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Waste minimization code'),
        ),
        migrations.AlterField(
            model_name='wasteline',
            name='epa_waste',
            field=models.BooleanField(verbose_name='Federal waste?'),
        ),
        migrations.AlterField(
            model_name='wasteline',
            name='line_number',
            field=models.PositiveIntegerField(verbose_name='Waste line number'),
        ),
    ]
