# Generated by Django 4.0.4 on 2022-04-18 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0023_delete_manifestsimple_remove_manifest_certified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 13, 59, 27, 991039), null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='originalSubmissionType',
            field=models.CharField(choices=[('FullElectronic', 'Full Electronic'), ('DataImage5Copy', 'Data + Image'), ('Hybrid', 'Hybrid'), ('Image', 'Image')], max_length=25, null=True),
        ),
    ]
