# Generated by Django 4.0.4 on 2022-05-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0023_rename_uom_wasteline_quantity_uom_wasteline_br_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteline',
            name='br_info',
            field=models.JSONField(verbose_name='BR information'),
        ),
    ]
