# Generated by Django 4.0.4 on 2022-05-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0024_alter_wasteline_br_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteline',
            name='pcb_info',
            field=models.JSONField(blank=True, null=True, verbose_name='PCB information'),
        ),
    ]
