# Generated by Django 4.0.4 on 2022-04-18 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0024_alter_manifest_createddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 14, 15, 46, 358756)),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='createdDate',
            field=models.DateTimeField(null=True),
        ),
    ]
