# Generated by Django 4.0.4 on 2022-05-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0025_alter_wasteline_pcb_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteline',
            name='federal_waste',
        ),
    ]
