# Generated by Django 4.0.4 on 2022-04-18 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0025_manifest_updateddate_alter_manifest_createddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epaSiteId', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='manifest',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 14, 47, 6, 433979)),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trak.handler'),
        ),
    ]
