# Generated by Django 4.0.4 on 2022-04-18 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0026_handler_alter_manifest_updateddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='generator',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 14, 48, 40, 832073)),
        ),
    ]
