# Generated by Django 4.0.4 on 2022-05-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0026_remove_wasteline_federal_waste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteline',
            name='br_info',
            field=models.JSONField(blank=True, null=True, verbose_name='BR information'),
        ),
    ]
