# Generated by Django 4.0.4 on 2022-05-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0028_alter_wasteline_discrepancy_residue_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wasteline',
            old_name='br_provided',
            new_name='br',
        ),
        migrations.RenameField(
            model_name='wasteline',
            old_name='pcb_info',
            new_name='pcb_infos',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='container_count',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='container_type',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='density',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='density_uom',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='discrepancy_comments',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='discrepancy_residue_info',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='dot_id',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='dot_printed_info',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='form_code',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='quantity_discrepancy',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='quantity_uom',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='residue',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='residue_comments',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='source_code',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='type_discrepancy',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='waste_description',
        ),
        migrations.RemoveField(
            model_name='wasteline',
            name='waste_minimization_code',
        ),
        migrations.AddField(
            model_name='wasteline',
            name='additional_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wasteline',
            name='discrepancy_info',
            field=models.BooleanField(blank=True, null=True, verbose_name='Discrepancy-Residue information'),
        ),
        migrations.AddField(
            model_name='wasteline',
            name='dot_info',
            field=models.JSONField(blank=True, null=True, verbose_name='DOT information'),
        ),
        migrations.AlterField(
            model_name='wasteline',
            name='epa_waste',
            field=models.BooleanField(verbose_name='Federal waste'),
        ),
        migrations.AlterField(
            model_name='wasteline',
            name='hazardous_waste',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wasteline',
            name='management_method',
            field=models.JSONField(blank=True, null=True, verbose_name='Management method code'),
        ),
        migrations.AlterField(
            model_name='wasteline',
            name='pcb',
            field=models.BooleanField(verbose_name='Contains PCBs'),
        ),
        migrations.AlterField(
            model_name='wasteline',
            name='quantity',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
