# Generated by Django 4.0.4 on 2022-04-18 20:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0028_alter_manifest_generator_alter_manifest_updateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trak.handler'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 16, 41, 53, 582093)),
        ),
    ]
