# Generated by Django 4.0.4 on 2022-04-18 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0029_alter_manifest_generator_alter_manifest_updateddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='handler',
            name='canEsign',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='contact',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='emergencyPhone',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='hasRegisteredEmanifestUser',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='hasSiteId',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='mailingAddress',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='name',
            field=models.CharField(default='1234', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='registered',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='siteAddress',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifest',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 16, 57, 57, 103172)),
        ),
    ]
