# Generated by Django 4.0.4 on 2022-04-18 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0030_handler_canesign_handler_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handler',
            name='hasSiteId',
        ),
        migrations.AlterField(
            model_name='manifest',
            name='updatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 18, 17, 0, 17, 941486)),
        ),
    ]
