# Generated by Django 4.0.4 on 2022-04-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0031_remove_handler_hassiteid_alter_manifest_updateddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='handler',
            name='electronicSignaturesInfo',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='handler',
            name='gisPrimary',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='limitedEsign',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='handler',
            name='modified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifest',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
