# Generated by Django 4.0.4 on 2022-04-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0032_handler_electronicsignaturesinfo_handler_gisprimary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='discrepancy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manifest',
            name='residueNewManifestTrackingNumbers',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifest',
            name='importFlag',
            field=models.BooleanField(null=True, verbose_name='import'),
        ),
    ]
