# Generated by Django 4.0.4 on 2022-05-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0032_remove_manifest_wastes_wasteline_manifest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteline',
            name='manifest',
        ),
    ]
