# Generated by Django 4.0.4 on 2022-04-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0033_manifest_discrepancy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='designatedFacility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Designated_Facility', to='trak.handler'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Generator', to='trak.handler'),
        ),
    ]
