# Generated by Django 4.0.4 on 2022-05-20 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0033_remove_wasteline_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteline',
            name='manifest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trak.manifest'),
            preserve_default=False,
        ),
    ]
