# Generated by Django 4.2.7 on 2024-02-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DotLookup',
        ),
        migrations.DeleteModel(
            name='WasteCode',
        ),
        migrations.AddField(
            model_name='handler',
            name='emergency_phone',
            field=models.ForeignKey(blank=True, help_text='Emergency phone number for the hazardous waste rcra_site', null=True, on_delete=django.db.models.deletion.PROTECT, to='trak.manifestphone'),
        ),
        migrations.DeleteModel(
            name='WasteLine',
        ),
    ]
