# Generated by Django 4.1.7 on 2023-04-14 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=2)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Locality",
                "verbose_name_plural": "Locality",
            },
        ),
        migrations.CreateModel(
            name="PortOfEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("city_port", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trak.locality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Port of Entry",
                "verbose_name_plural": "Port of Entry",
            },
        ),
        migrations.CreateModel(
            name="ImportInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("import_generator", models.JSONField(blank=True, null=True)),
                (
                    "port_of_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trak.portofentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Info",
                "verbose_name_plural": "Import Info",
            },
        ),
    ]
