# Generated by Django 4.1.4 on 2022-12-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rcraprofile',
            old_name='rcra_user_name',
            new_name='rcra_username',
        ),
        migrations.AddField(
            model_name='rcraprofile',
            name='email',
            field=models.EmailField(default='john.doe@haztrak.net', max_length=254),
            preserve_default=False,
        ),
    ]
