# Generated by Django 4.1.7 on 2023-06-15 05:12

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RejectionInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("transporter_on_site", models.BooleanField(blank=True, null=True)),
                (
                    "rejection_type",
                    models.CharField(
                        blank=True,
                        choices=[("FR", "Full Rejection"), ("PR", "Partial Rejection")],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "alternate_designated_facility_type",
                    models.CharField(
                        blank=True,
                        choices=[("GEN", "Generator"), ("TSD", "Tsdf")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "new_manifest_tracking_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200, null=True),
                        default=list,
                        size=None,
                    ),
                ),
                ("rejection_comments", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "alternate_designated_facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trak.handler",
                    ),
                ),
                (
                    "generator_electronic_signature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trak.esignature",
                    ),
                ),
                (
                    "generator_paper_signature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trak.papersignature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rejection Info",
                "verbose_name_plural": "Rejection Info",
            },
        ),
    ]
