# Generated by Django 4.1.7 on 2023-04-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("trak", "0002_locality_portofentry_importinfo"),
        ("trak", "0003_alter_portofentry_options_alter_portofentry_state_and_more"),
    ]

    dependencies = [
        ("trak", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortOfEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("city_port", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AK", "Alaska"),
                            ("AL", "Alabama"),
                            ("AP", "Armed Forces Pacific"),
                            ("AR", "Arkansas"),
                            ("AZ", "Arizona"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DC", "Washington DC"),
                            ("DE", "Delaware"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("GU", "Guam"),
                            ("HI", "Hawaii"),
                            ("IA", "Iowa"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("MA", "Massachusetts"),
                            ("MD", "Maryland"),
                            ("ME", "Maine"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MO", "Missouri"),
                            ("MS", "Mississippi"),
                            ("MT", "Montana"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("NE", "Nebraska"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NV", "Nevada"),
                            ("NY", "New York"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("PR", "Puerto Rico"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VA", "Virginia"),
                            ("VI", "Virgin Islands"),
                            ("VT", "Vermont"),
                            ("WA", "Washington"),
                            ("WI", "Wisconsin"),
                            ("WV", "West Virginia"),
                            ("WY", "Wyoming"),
                            ("XA", "REGION 01 PURVIEW"),
                            ("XB", "REGION 02 PURVIEW"),
                            ("XC", "REGION 03 PURVIEW"),
                            ("XD", "REGION 04 PURVIEW"),
                            ("XE", "REGION 05 PURVIEW"),
                            ("XF", "REGION 06 PURVIEW"),
                            ("XG", "REGION 07 PURVIEW"),
                            ("XH", "REGION 08 PURVIEW"),
                            ("XI", "REGION 09 PURVIEW"),
                            ("XJ", "REGION 10 PURVIEW"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Port of Entry",
                "verbose_name_plural": "Ports of Entry",
            },
        ),
        migrations.CreateModel(
            name="ImportInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("import_generator", models.JSONField(blank=True, null=True)),
                (
                    "port_of_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trak.portofentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Info",
                "verbose_name_plural": "Import Info",
            },
        ),
    ]
