# Generated by Django 4.1.3 on 2022-12-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='site_type',
            field=models.CharField(choices=[('designatedFacility', 'Tsdf'), ('generator', 'Generator'), ('transporter', 'Transporter'), ('broker', 'Broker')], max_length=20),
        ),
    ]
