# Generated by Django 4.1.4 on 2023-01-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rcraprofile",
            name="rcra_username",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
