# Generated by Django 4.1.7 on 2023-03-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="handler",
            name="electronic_signatures_info",
        ),
        migrations.RemoveField(
            model_name="manifesthandler",
            name="elec_signatures_info",
        ),
        migrations.AddField(
            model_name="manifesthandler",
            name="electronic_signatures",
            field=models.JSONField(blank=True, null=True, verbose_name="e-signature"),
        ),
    ]
