# Generated by Django 4.1.4 on 2023-01-05 01:45

import apps.trak.models.handler
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0002_alter_transporter_manifest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='epa_site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trak.handler', verbose_name=apps.trak.models.handler.Handler),
        ),
    ]
