# Generated by Django 4.1.7 on 2023-03-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0002_remove_manifest_locked_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("printed_name", models.CharField(max_length=255)),
                ("sign_date", models.DateTimeField()),
            ],
        ),
    ]
