# Generated by Django 4.1.7 on 2023-03-09 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0002_remove_manifest_locked_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("printed_name", models.CharField(max_length=255)),
                ("sign_date", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="manifesthandler",
            name="handler",
            field=models.ForeignKey(
                help_text="Hazardous waste handler associated with the manifest",
                on_delete=django.db.models.deletion.CASCADE,
                to="trak.handler",
            ),
        ),
        migrations.AddField(
            model_name="manifesthandler",
            name="paper_signature",
            field=models.OneToOneField(
                blank=True,
                help_text="The signature associated with hazardous waste custody exchange",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trak.papersignature",
            ),
        ),
    ]
