# Generated by Django 4.1.4 on 2023-01-03 21:39

import django.db.models.deletion
from django.db import migrations, models

import apps.trak.models.contact


class Migration(migrations.Migration):

    replaces = [('trak', '0003_epaphone_contact'), ('trak', '0004_alter_handler_contact')]

    dependencies = [
        ('trak', '0002_rename_rcra_user_name_rcraprofile_rcra_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpaPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', apps.trak.models.contact.EpaPhoneNumber(max_length=12)),
                ('extension', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=38, null=True)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('last_name', models.CharField(blank=True, max_length=38, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=80, null=True)),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trak.epaphone')),
            ],
        ),
        migrations.AlterField(
            model_name='handler',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trak.contact', verbose_name='Contact Information'),
        ),
    ]
