# Generated by Django 4.1.7 on 2023-03-03 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0002_remove_handler_electronic_signatures_info_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transporter",
            name="handler",
        ),
        migrations.RemoveField(
            model_name="transporter",
            name="id",
        ),
        migrations.AddField(
            model_name="transporter",
            name="manifesthandler_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="trak.manifesthandler",
            ),
            preserve_default=False,
        ),
    ]
