# Generated by Django 4.1.7 on 2023-03-04 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0002_signer_esignature"),
    ]

    operations = [
        migrations.AddField(
            model_name="esignature",
            name="manifest_handler",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="trak.manifesthandler"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="esignature",
            name="signer",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="trak.signer"
            ),
        ),
    ]
