# Generated by Django 4.1.4 on 2023-01-09 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0003_alter_site_epa_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_manager', models.BooleanField(default=False)),
                ('annual_report', models.CharField(choices=[('C', 'Certifier'), ('P', 'Preparer'), ('V', 'Viewer')], max_length=1)),
                ('biennial_report', models.CharField(choices=[('C', 'Certifier'), ('P', 'Preparer'), ('V', 'Viewer')], max_length=1)),
                ('e_manifest', models.CharField(choices=[('C', 'Certifier'), ('P', 'Preparer'), ('V', 'Viewer')], max_length=1)),
                ('my_rcra_id', models.CharField(choices=[('C', 'Certifier'), ('P', 'Preparer'), ('V', 'Viewer')], max_length=1)),
                ('wiets', models.CharField(choices=[('C', 'Certifier'), ('P', 'Preparer'), ('V', 'Viewer')], max_length=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trak.rcraprofile')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trak.site')),
            ],
        ),
    ]
