# Generated by Django 4.1.7 on 2023-03-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0003_esignature_manifest_handler_alter_esignature_signer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manifest",
            old_name="locked_reason",
            new_name="lock_reason",
        ),
        migrations.AlterField(
            model_name="manifest",
            name="original_sub_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FullElectronic", "Full Electronic"),
                    ("DataImage5Copy", "Data + Image"),
                    ("Hybrid", "Hybrid"),
                    ("Image", "Image"),
                ],
                max_length=25,
                null=True,
                verbose_name="Original Submission Type",
            ),
        ),
    ]
