# Generated by Django 4.1.4 on 2023-01-11 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0003_alter_site_epa_site_sitepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepermission',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_permission', to='trak.rcraprofile'),
        ),
    ]
