# Generated by Django 4.1.7 on 2023-03-10 11:36

import apps.trak.models.manifest_model
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0003_papersignature_alter_manifesthandler_handler_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "original_mtn",
                    models.JSONField(
                        blank=True,
                        help_text="Original manifest tracking number of rejected manifestRegex expression validation: [0-9]{9}[A-Z]{3}",
                        null=True,
                        validators=[apps.trak.models.manifest_model.validate_mtn],
                    ),
                ),
                (
                    "new_destination",
                    models.CharField(
                        blank=True,
                        choices=[("GEN", "Generator"), ("TSD", "Tsdf")],
                        help_text="Destination of the new manifest created during rejection or residue.",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("consent_number", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "handling_instructions",
                    models.CharField(
                        blank=True,
                        help_text="Special Handling Instructions",
                        max_length=4000,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "AdditionalInfo",
                "verbose_name_plural": "AdditionalInfo",
            },
        ),
        migrations.AlterField(
            model_name="manifest",
            name="mtn",
            field=models.CharField(
                default=apps.trak.models.manifest_model.draft_mtn,
                max_length=30,
                unique=True,
                validators=[apps.trak.models.manifest_model.validate_mtn],
                verbose_name="manifest Tracking Number",
            ),
        ),
    ]
