# Generated by Django 4.1.4 on 2023-01-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0004_sitepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepermission',
            name='annual_report',
            field=models.CharField(choices=[('Certifier', 'Certifier'), ('Preparer', 'Preparer'), ('Viewer', 'Viewer')], max_length=12),
        ),
        migrations.AlterField(
            model_name='sitepermission',
            name='biennial_report',
            field=models.CharField(choices=[('Certifier', 'Certifier'), ('Preparer', 'Preparer'), ('Viewer', 'Viewer')], max_length=12),
        ),
        migrations.AlterField(
            model_name='sitepermission',
            name='e_manifest',
            field=models.CharField(choices=[('Certifier', 'Certifier'), ('Preparer', 'Preparer'), ('Viewer', 'Viewer')], max_length=12),
        ),
        migrations.AlterField(
            model_name='sitepermission',
            name='my_rcra_id',
            field=models.CharField(choices=[('Certifier', 'Certifier'), ('Preparer', 'Preparer'), ('Viewer', 'Viewer')], max_length=12),
        ),
        migrations.AlterField(
            model_name='sitepermission',
            name='wiets',
            field=models.CharField(choices=[('Certifier', 'Certifier'), ('Preparer', 'Preparer'), ('Viewer', 'Viewer')], max_length=12),
        ),
    ]
