# Generated by Django 4.1.6 on 2023-02-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0004_alter_handler_epa_id_alter_site_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcraprofile',
            name='epa_sites',
        ),
    ]
