# Generated by Django 4.1.7 on 2023-03-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0004_additionalinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
