# Generated by Django 4.2.4 on 2023-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0004_federal_waste_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manifest",
            name="rejection",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
