# Generated by Django 4.1.7 on 2023-03-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0004_rename_locked_reason_manifest_lock_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manifest",
            name="lock_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACS", "AsyncSign"),
                    ("ECB", "EpaChangeBiller"),
                    ("EPC", "EpaCorrection"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
