# Generated by Django 4.1.7 on 2023-03-06 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0005_alter_manifest_lock_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manifesthandler",
            name="electronic_signatures",
        ),
        migrations.AlterField(
            model_name="esignature",
            name="manifest_handler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="e_signature",
                to="trak.manifesthandler",
            ),
        ),
        migrations.AlterField(
            model_name="esignature",
            name="signer",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="trak.signer"
            ),
        ),
    ]
