# Generated by Django 4.2.5 on 2023-10-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0005_alter_manifest_rejection"),
    ]

    operations = [
        migrations.CreateModel(
            name="DotLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("ID", "Id"),
                            ("GROUP", "Group"),
                            ("NAME", "Name"),
                            ("CLASS", "Class"),
                        ],
                        max_length=5,
                    ),
                ),
            ],
            options={
                "ordering": ["value_type", "value"],
            },
        ),
    ]
