# Generated by Django 4.2.7 on 2023-12-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0006_dot_shipping_names'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wasteline',
            unique_together={('manifest', 'line_number')},
        ),
    ]
