# Generated by Django 4.1.7 on 2023-03-06 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0006_remove_manifesthandler_electronic_signatures_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esignature",
            name="manifest_handler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="e_signatures",
                to="trak.manifesthandler",
            ),
        ),
    ]
