# Generated by Django 4.1.7 on 2023-03-06 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0007_alter_esignature_manifest_handler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esignature",
            name="on_behalf",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="esignature",
            name="signer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trak.signer",
            ),
        ),
    ]
