# Generated by Django 4.1.7 on 2023-03-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0007_wastecode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wastecode",
            name="code",
            field=models.CharField(max_length=4),
        ),
    ]
