# Generated by Django 4.2.5 on 2023-10-11 00:01

from django.db import migrations

from apps.trak.models import DotOption
from apps.trak.models.waste_models import DotOptionType


def populate_dot_packing_groups(apps, schema_editor):
    # WasteCode = apps.get_model("trak", "WasteCode")

    # Replace this with your logic to fetch state waste codes from RCRAInfo
    packing_groups = [
        {"value": "I", "value_type": DotOptionType.GROUP},
        {"value": "II", "value_type": DotOptionType.GROUP},
        {"value": "III", "value_type": DotOptionType.GROUP},
    ]

    for group in packing_groups:
        DotOption.objects.create(**group)


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0007_dot_id_numbers"),
    ]

    operations = [
        migrations.RunPython(populate_dot_packing_groups),
    ]
