# Generated by Django 4.1.7 on 2023-03-30 23:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0008_alter_wastecode_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["first_name"]},
        ),
        migrations.AlterModelOptions(
            name="manifest",
            options={"ordering": ["update_date", "mtn"]},
        ),
        migrations.AlterModelOptions(
            name="manifesthandler",
            options={"ordering": ["handler"]},
        ),
        migrations.AlterModelOptions(
            name="rcraprofile",
            options={"ordering": ["rcra_username"]},
        ),
        migrations.AlterModelOptions(
            name="signer",
            options={"ordering": ["first_name"]},
        ),
    ]
