# Generated by Django 4.2.7 on 2023-11-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0009_dot_shipping_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('voice', 'Voice'), ('text', 'Text')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='signer_role',
            field=models.CharField(choices=[('Industry', 'Industry'), ('PPC', 'Ppc'), ('EPA', 'Epa'), ('State', 'State')], max_length=10, null=True),
        ),
    ]
