# Generated by Django 4.1.7 on 2023-03-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0009_alter_handler_site_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManifestHandler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "elec_signatures_info",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Electronic signature info"
                    ),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="trak.handler"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="manifest",
            name="generator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generator",
                to="trak.manifesthandler",
            ),
        ),
        migrations.AlterField(
            model_name="manifest",
            name="tsd",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="designated_facility",
                to="trak.manifesthandler",
                verbose_name="Designated facility",
            ),
        ),
    ]
