# Generated by Django 4.2.7 on 2023-11-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0010_alter_signer_contact_type_alter_signer_signer_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dotlookup',
            options={'ordering': ['value_type', 'value'], 'verbose_name': 'DOT lookup', 'verbose_name_plural': 'DOT lookups'},
        ),
    ]
