# Generated by Django 4.1.7 on 2023-03-31 00:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0010_alter_esignature_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="additionalinfo",
            options={"verbose_name": "Additional Info", "verbose_name_plural": "Additional Info"},
        ),
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ["address1"]},
        ),
        migrations.AlterModelOptions(
            name="epaphone",
            options={"ordering": ["number"]},
        ),
        migrations.AlterModelOptions(
            name="handler",
            options={"ordering": ["epa_id"]},
        ),
        migrations.AlterModelOptions(
            name="papersignature",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="site",
            options={"ordering": ["epa_site__epa_id"]},
        ),
        migrations.AlterModelOptions(
            name="sitepermission",
            options={
                "ordering": ["site__epa_site__epa_id"],
                "verbose_name": "EPA Site Permission",
            },
        ),
        migrations.AlterModelOptions(
            name="transporter",
            options={"ordering": ["manifest__mtn"]},
        ),
        migrations.AlterModelOptions(
            name="wastecode",
            options={"ordering": ["code"]},
        ),
        migrations.AlterModelOptions(
            name="wasteline",
            options={"ordering": ["manifest__mtn", "line_number"]},
        ),
    ]
