# Generated by Django 4.1.7 on 2023-03-31 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0011_alter_additionalinfo_options_alter_address_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manifest",
            name="generator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="manifest_foo",
                to="trak.manifesthandler",
            ),
        ),
    ]
