# Generated by Django 4.1.7 on 2023-03-31 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trak", "0012_alter_manifest_generator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manifest",
            name="generator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generator",
                to="trak.manifesthandler",
            ),
        ),
    ]
