# This file will apply these (already existing) labels to PR upon opening.
test:
  - client/src/**/*.spec.ts
  - client/src/**/*.spec.tsx
  - server/apps/trak/tests/**/*

django:
  - server/**/*

reactjs:
  - client/**/*

CI/CD:
  - any: ['.github/workflows/**.yaml', '**/*Dockerfile', '**/*.dockerignore']

documentation:
  - any: ['docs/**/*', 'docs/haztrak_book/**/*', '**/README.md']

dependencies:
  - any:
      [
        'server/requirements.txt',
        'server/requirements_dev.txt',
        'client/package.json',
        'client/package-lock.json',
      ]

database:
  - server/apps/**/migrations/*.py
