# This file will apply these (already existing) labels to PR upon opening.
infrastructure:
  - any: ['docker-compose.yaml', 'infra/**/*.tf']

CI/CD:
  - any: ['.github/**/*', '**/*Dockerfile', '**/*.dockerignore']

documentation:
  - any: ['docs/**/*', 'docs/haztrak_book/**/*', '**/README.md']

dependencies:
  - any:
      [
        'server/requirements.txt',
        'server/requirements_dev.txt',
        'client/package.json',
        'client/package-lock.json',
      ]

database:
  - server/apps/**/migrations/*.py
