# This file will apply these (already existing) labels to PR upon opening.
test:
  - client/src/**/*.spec.ts
  - client/src/**/*.spec.tsx
  - server/apps/trak/tests/**/*

django:
  - server/**/*

reactjs:
  - client/**/*

CI/CD:
  - .github/workflows/**.yaml

documentation:
  - any: ['docs/**/*', '**/README.md']

dependencies:
  - any: ['server/requirements.txt', 'client/package.json', 'client/package-lock.json']

database:
  - server/apps/**/migrations/*.py
