name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

# map PR labels to changelog categories
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: ':nut_and_bolt: Maintenance'
    labels:
      - 'chore'
      - 'infrastructure'
      - 'documentation'

exclude-labels:
  - 'skip-changelog'

# map PR labels to semantic version updates (e.g., if  a feature is added, the minor version is incremented)
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'chore'
      - 'infrastructure'
  default: patch

# used for auto-labeling PRs, used instead of actions/labeler
# https://github.com/release-drafter/release-drafter#autolabeler
autolabeler:
  - label: 'client'
    files:
      - '*.tsx'

# template for the release notes (changelog)
template: |
  ## Changes

  $CHANGES

  ## Contributor

  $CONTRIBUTORS
