name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: ':nut_and_bolt: Maintenance'
    labels:
      - 'chore'
      - 'infrastructure'
      - 'documentation'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'chore'
      - 'infrastructure'
  default: patch
template: |
  ## Changes

  $CHANGES

  ## Contributor

  $CONTRIBUTORS
