# Generated by Django 4.0.4 on 2022-06-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0009_alter_address_country'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='epa_sites',
            field=models.ManyToManyField(related_name='sites', to='trak.site'),
        ),
    ]
