# Generated by Django 4.0.3 on 2022-04-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_address_address2'),
        ('accounts', '0002_profile_epa_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='epa_sites',
            field=models.ManyToManyField(null=True, to='sites.epasite'),
        ),
    ]
