# Generated by Django 4.0.4 on 2022-04-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_epa_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rcra_api_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rcra_api_key',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
