# Generated by Django 5.0.6 on 2024-07-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
