# Generated by Django 5.0.6 on 2024-07-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_grouppermission_userpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
