# Generated by Django 4.0.3 on 2022-04-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='created date')),
                ('update_date', models.DateTimeField(verbose_name='update date')),
                ('manifest_tracking_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('notAssigned', 'Not Assigned'), ('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('InTransit', 'In Transit'), ('ReadyForSignature', 'Ready for Signature'), ('Signed', 'Signed'), ('Corrected', 'Corrected'), ('UnderCorrection', 'Under Correction'), ('MtnValidationFailed', 'MTN Validation Failed')], default='notAssigned', max_length=25)),
                ('submission_type', models.CharField(choices=[('FullElectronic', 'Full Electronic'), ('DataImage5Copy', 'Data + Image'), ('Hybrid', 'Hybrid'), ('Image', 'Image')], default='FullElectronic', max_length=25)),
                ('origin_type', models.CharField(choices=[('Web', 'Web'), ('Service', 'Service'), ('Mail', 'Mail')], default='Service', max_length=25)),
                ('shipped_date', models.DateTimeField(verbose_name='shipped date')),
                ('potential_ship_date', models.CharField(max_length=15)),
                ('received_date', models.DateTimeField(verbose_name='received date')),
                ('certified_date', models.DateTimeField(verbose_name='certified date')),
                ('generator_id', models.CharField(max_length=25)),
                ('tsd_id', models.CharField(max_length=25)),
            ],
        ),
    ]
