# Generated by Django 4.0.3 on 2022-03-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manifest',
        ),
    ]
