# Generated by Django 4.0.3 on 2022-04-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='signature_status',
            field=models.BooleanField(default=False),
        ),
    ]
