# Generated by Django 4.0.3 on 2022-04-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0002_manifest_is_public_manifest_signature_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='manifest',
            name='signature_status',
        ),
    ]
