# Generated by Django 4.0.3 on 2022-03-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trak', '0002_delete_manifest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(verbose_name='created date')),
                ('update_date', models.DateTimeField(verbose_name='update date')),
                ('manifest_tracking_number', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=25)),
            ],
        ),
    ]
