# Generated by Django 4.0.3 on 2022-04-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0003_remove_manifest_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='contains_rejected_residue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manifest',
            name='import_waste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manifest',
            name='rejection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manifest',
            name='residue',
            field=models.BooleanField(default=False),
        ),
    ]
