# Generated by Django 4.0.3 on 2022-03-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='generator',
            field=models.CharField(default=str, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifest',
            name='tsd',
            field=models.CharField(default=str, max_length=25),
            preserve_default=False,
        ),
    ]
