# Generated by Django 4.0.3 on 2022-04-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0004_manifest_contains_rejected_residue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='certified_date',
            field=models.DateTimeField(null=True, verbose_name='certified date'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='potential_ship_date',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='received_date',
            field=models.DateTimeField(null=True, verbose_name='received date'),
        ),
    ]
