# Generated by Django 4.0.3 on 2022-04-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0005_alter_manifest_certified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='shipped_date',
            field=models.DateTimeField(null=True, verbose_name='shipped date'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='update date'),
        ),
    ]
