# Generated by Django 4.2.7 on 2024-02-15 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trak', '0001_initial'),
        ('manifest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generator', to='trak.handler'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='tsdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designated_facility', to='trak.handler', verbose_name='designated facility'),
        ),
        migrations.AddField(
            model_name='importinfo',
            name='port_of_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manifest.portofentry'),
        ),
    ]
