# Generated by Django 5.0.4 on 2024-05-28 22:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_rename_trakorg_org'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrakOrgAccess',
            new_name='OrgAccess',
        ),
    ]
