# Generated by Django 4.0.3 on 2022-03-22 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manifest',
        ),
    ]
