# Generated by Django 4.0.3 on 2022-04-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_address_address2'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='epa_sites',
            field=models.ManyToManyField(to='sites.epasite'),
        ),
    ]
