# Generated by Django 5.0.4 on 2024-06-03 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='papersignature',
            options={},
        ),
    ]
