# Generated by Django 4.2.10 on 2024-02-16 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rcrasite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haztraksite',
            name='rcra_site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rcrasite.rcrasite', verbose_name='rcra_site'),
        ),
        migrations.AddField(
            model_name='haztrakprofile',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haztrak_profiles', to='core.haztrakorg'),
        ),
        migrations.AddField(
            model_name='haztrakprofile',
            name='rcrainfo_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haztrak_profile', to='core.rcrainfoprofile'),
        ),
        migrations.AddField(
            model_name='haztrakprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='haztrak_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='haztrakorg',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='haztrakuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='haztrakuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
