# Generated by Django 4.2.7 on 2023-11-03 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_haztrakprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="haztrakprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="haztrak_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
