# Generated by Django 4.2.7 on 2023-11-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_haztrakprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haztrakprofile',
            options={'default_related_name': 'haztrak_profile', 'ordering': ['user__username'], 'verbose_name': 'Haztrak Profile'},
        ),
        migrations.AlterModelOptions(
            name='haztrakuser',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='rcraprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='haztrakprofile',
            name='rcrainfo_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haztrak_profile', to='core.rcraprofile'),
        ),
    ]
