# Generated by Django 4.2.7 on 2023-11-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_haztrakprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="haztrakprofile",
            name="admin_rcrainfo_profile",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.rcraprofile",
            ),
        ),
    ]
