# Generated by Django 4.2.7 on 2023-11-16 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_rcrasite_options_and_more'),
        ('core', '0003_alter_haztrakprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='haztrakprofile',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='haztrak_profiles', to='sites.haztrakorg'),
        ),
    ]
