# Generated by Django 4.2.7 on 2023-11-08 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_haztrakprofile_admin_rcrainfo_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="haztrakprofile",
            name="admin_rcrainfo_profile",
        ),
    ]
