# Generated by Django 4.2.10 on 2024-02-17 01:25

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("org", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RcrainfoProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("rcra_api_key", models.CharField(blank=True, max_length=128, null=True)),
                ("rcra_api_id", models.CharField(blank=True, max_length=128, null=True)),
                ("rcra_username", models.CharField(blank=True, max_length=128, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "ordering": ["rcra_username"],
            },
        ),
        migrations.CreateModel(
            name="HaztrakProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("org", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="haztrak_profiles", to="org.haztrakorg")),
                ("rcrainfo_profile", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="haztrak_profile", to="profile.rcrainfoprofile")),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="haztrak_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Haztrak Profile",
                "ordering": ["user__username"],
                "default_related_name": "haztrak_profile",
            },
        ),
    ]
