# Generated by Django 4.0.3 on 2022-04-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_epasite_gis_primary_epasite_mailing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
