# Generated by Django 4.1.7 on 2023-04-01 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinValueValidator(
                                2, "site aliases must be longer than 2 characters"
                            )
                        ],
                        verbose_name="site alias",
                    ),
                ),
                (
                    "last_rcra_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last sync with RCRAInfo"
                    ),
                ),
            ],
            options={
                "ordering": ["epa_site__epa_id"],
            },
        ),
    ]
