# Generated by Django 4.2.7 on 2023-11-03 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_haztrakprofile"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitePermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emanifest",
                    models.CharField(
                        choices=[
                            ("viewer", "view"),
                            ("editor", "edit"),
                            ("signer", "sign"),
                        ],
                        default="view",
                        max_length=6,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_permissions",
                        to="core.haztrakprofile",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Permissions",
            },
        ),
    ]
