# Generated by Django 4.1.7 on 2023-04-11 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rcrasitepermission",
            options={
                "ordering": ["site__rcra_site__epa_id"],
                "verbose_name": "RCRA Site Permission",
            },
        ),
        migrations.AlterModelOptions(
            name="site",
            options={
                "ordering": ["rcra_site__epa_id"],
                "verbose_name": "Haztrak Site",
                "verbose_name_plural": "Haztrak Sites",
            },
        ),
    ]
