# Generated by Django 4.2.7 on 2023-11-08 23:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_haztrakprofile"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HaztrakSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinValueValidator(
                                2, "site aliases must be longer than 2 characters"
                            )
                        ],
                        verbose_name="site alias",
                    ),
                ),
                (
                    "last_rcrainfo_manifest_sync",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="last RCRAInfo manifest sync date",
                    ),
                ),
                (
                    "admin_rcrainfo_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.rcraprofile",
                    ),
                ),
                (
                    "rcra_site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.rcrasite",
                        verbose_name="rcra_site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Haztrak Site",
                "verbose_name_plural": "Haztrak Sites",
                "ordering": ["rcra_site__epa_id"],
            },
        ),
        migrations.CreateModel(
            name="SitePermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emanifest",
                    models.CharField(
                        choices=[
                            ("viewer", "view"),
                            ("editor", "edit"),
                            ("signer", "sign"),
                        ],
                        default="view",
                        max_length=6,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_permissions",
                        to="core.haztrakprofile",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.haztraksite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Permissions",
            },
        ),
        migrations.RenameModel(
            old_name="RcraSitePermission",
            new_name="RcraSitePermissions",
        ),
        migrations.AlterModelOptions(
            name="rcrasitepermissions",
            options={
                "ordering": ["site__epa_id"],
                "verbose_name": "RCRA Site Permission",
            },
        ),
        migrations.AlterField(
            model_name="rcrasitepermissions",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sites.rcrasite"
            ),
        ),
        migrations.DeleteModel(
            name="Site",
        ),
    ]
