# Generated by Django 4.1.7 on 2023-04-01 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trak", "0001_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="epa_site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="trak.epasite",
                verbose_name="epa_site",
            ),
        ),
    ]
