# Generated by Django 4.2.7 on 2023-11-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_sitepermissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="last_rcra_sync",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last RCRAInfo manifest sync date"
            ),
        ),
    ]
