# Generated by Django 4.2.7 on 2023-11-09 14:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_haztrakprofile'),
        ('sites', '0002_haztraksite_sitepermissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haztraksite',
            name='admin_rcrainfo_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rcraprofile', verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='haztraksite',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'site aliases must be longer than 2 characters')], verbose_name='site alias'),
        ),
    ]
