# Generated by Django 4.2.7 on 2023-11-10 16:35

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_haztraksite_sitepermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaztrakOrg',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.AlterField(
            model_name='haztraksite',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'site aliases must be longer than 2 characters')], verbose_name='site alias'),
        ),
    ]
