# Generated by Django 4.2.7 on 2023-11-08 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_haztrakprofile_admin_rcrainfo_profile"),
        ("sites", "0003_alter_site_last_rcrainfo_manifest_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="admin_rcrainfo_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.rcraprofile",
            ),
        ),
    ]
