# Generated by Django 4.2.7 on 2023-11-16 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0003_alter_haztraksite_admin_rcrainfo_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rcrasite',
            options={'ordering': ['epa_id'], 'verbose_name': 'RCRAInfo Site', 'verbose_name_plural': 'RCRAInfo Sites'},
        ),
        migrations.AlterModelOptions(
            name='rcrasitepermissions',
            options={'ordering': ['site__epa_id'], 'verbose_name': 'RCRAInfo Permission', 'verbose_name_plural': 'RCRAInfo Permissions'},
        ),
        migrations.AlterModelOptions(
            name='sitepermissions',
            options={'ordering': ['profile'], 'verbose_name': 'Site Permission', 'verbose_name_plural': 'Site Permissions'},
        ),
        migrations.RemoveField(
            model_name='haztraksite',
            name='admin_rcrainfo_profile',
        ),
        migrations.AlterField(
            model_name='rcrasite',
            name='site_type',
            field=models.CharField(blank=True, choices=[('Generator', 'Generator'), ('Transporter', 'Transporter'), ('Tsdf', 'Tsdf'), ('Broker', 'Broker')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='HaztrakOrg',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='haztraksite',
            name='org',
            field=models.ForeignKey(default='efb9e104-7f61-4365-a9af-9d7b55c854c4', on_delete=django.db.models.deletion.CASCADE, to='sites.haztrakorg'),
            preserve_default=False,
        ),
    ]
