# Generated by Django 4.2.7 on 2023-11-08 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0004_site_admin_rcrainfo_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="last_rcra_sync",
            new_name="last_rcrainfo_manifest_sync",
        ),
    ]
