# Generated by Django 4.2.7 on 2023-11-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_haztrakorg_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haztrakorg',
            options={'ordering': ['name'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='rcrasite',
            options={'ordering': ['epa_id'], 'verbose_name': 'RCRAInfo Site', 'verbose_name_plural': 'RCRAInfo Sites'},
        ),
        migrations.AlterModelOptions(
            name='rcrasitepermissions',
            options={'ordering': ['site__epa_id'], 'verbose_name': 'RCRAInfo Permission', 'verbose_name_plural': 'RCRAInfo Permissions'},
        ),
        migrations.AlterModelOptions(
            name='sitepermissions',
            options={'ordering': ['profile'], 'verbose_name': 'Site Permission', 'verbose_name_plural': 'Site Permissions'},
        ),
        migrations.RemoveField(
            model_name='haztraksite',
            name='admin_rcrainfo_profile',
        ),
        migrations.AddField(
            model_name='haztraksite',
            name='org',
            field=models.ForeignKey(default='efb9e104-7f61-4365-a9af-9d7b55c854c4', on_delete=django.db.models.deletion.CASCADE, to='sites.haztrakorg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rcrasite',
            name='site_type',
            field=models.CharField(blank=True, choices=[('Generator', 'Generator'), ('Transporter', 'Transporter'), ('Tsdf', 'Tsdf'), ('Broker', 'Broker')], max_length=20, null=True),
        ),
    ]
