# Generated by Django 4.2.7 on 2023-11-14 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0005_alter_haztrakorg_options_alter_rcrasite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haztrakorg',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
