# Generated by Django 4.2.7 on 2023-11-08 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_haztrakprofile_admin_rcrainfo_profile"),
        ("sites", "0005_rename_last_rcra_sync_site_last_rcrainfo_manifest_sync"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Site",
            new_name="HaztrakSite",
        ),
    ]
