# Generated by Django 4.2.7 on 2023-11-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0006_rename_site_haztraksite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rcrasitepermission",
            options={
                "ordering": ["site__epa_id"],
                "verbose_name": "RCRA Site Permission",
            },
        ),
        migrations.AlterField(
            model_name="rcrasitepermission",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sites.rcrasite"
            ),
        ),
    ]
