# Generated by Django 4.2.7 on 2023-11-08 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_haztrakprofile_admin_rcrainfo_profile"),
        ("sites", "0007_alter_rcrasitepermission_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RcraSitePermission",
            new_name="RcraSitePermissions",
        ),
    ]
