apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    {{- include "haztrak-charts.labels" . | nindent 4 }}
type: Opaque
data:
  djangoSecretKey: {{ "django-insecure-%btjqoun@6ps$e@8bw$48s+!x1e4aiz&5p2nrf6cmiw4)jsx5d" | b64enc }}
