apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    {{- include "haztrak-charts.labels" . | nindent 4 }}
type: Opaque
data:
  djangoSecretKey: {{ .Values.django.secretKey | b64enc }}
  dbPassword: {{ .Values.db.password | b64enc }}
  dbUser: {{ .Values.db.user | b64enc }}
