# Generated by Django 5.0.4 on 2024-06-03 01:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrakProfile',
            new_name='Profile',
        ),
    ]
