# Generated by Django 5.0.8 on 2024-08-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0002_rename_trakprofile_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="users/%Y/%m/%d/"),
        ),
    ]
