# Generated by Django 4.0.3 on 2022-04-05 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epasite',
            name='gis_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='epasite',
            name='mailing_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_address', to='sites.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='epasite',
            name='site_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='site_address', to='sites.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='epasite',
            name='can_esign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='epasite',
            name='limited_esign',
            field=models.BooleanField(default=True),
        ),
    ]
