# Generated by Django 4.0.3 on 2022-04-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_address_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='street_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
