# Generated by Django 5.0.7 on 2024-07-24 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgsite', '0003_alter_sitegroupobjectpermission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteaccess',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgsite.site'),
        ),
        migrations.AlterField(
            model_name='sitegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgsite.site'),
        ),
        migrations.AlterField(
            model_name='siteuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgsite.site'),
        ),
    ]
