# Generated by Django 5.0.7 on 2024-07-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgsite', '0004_alter_siteaccess_site_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteAccess',
        ),
    ]
