# Generated by Django 4.0.4 on 2022-06-08 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trak', '0002_address_remove_handler_mail_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='mail_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mail_address', to='trak.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handler',
            name='site_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='site_address', to='trak.address'),
            preserve_default=False,
        ),
    ]
