# Generated by Django 5.0.8 on 2024-08-22 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handler", "0003_alter_papersignature_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="handler",
            name="emergency_phone",
        ),
        migrations.RemoveField(
            model_name="handler",
            name="paper_signature",
        ),
        migrations.RemoveField(
            model_name="handler",
            name="rcra_site",
        ),
        migrations.RemoveField(
            model_name="transporter",
            name="handler_ptr",
        ),
        migrations.RemoveField(
            model_name="signer",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="transporter",
            name="manifest",
        ),
        migrations.DeleteModel(
            name="ESignature",
        ),
        migrations.DeleteModel(
            name="PaperSignature",
        ),
    ]
