# Generated by Django 5.0.8 on 2024-08-22 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("handler", "0004_remove_handler_emergency_phone_and_more"),
        ("manifest", "0002_handler_manifestphone_papersignature_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Handler",
        ),
        migrations.DeleteModel(
            name="ManifestPhone",
        ),
        migrations.DeleteModel(
            name="Signer",
        ),
        migrations.DeleteModel(
            name="Transporter",
        ),
    ]
