# Generated by Django 4.2.10 on 2024-02-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manifest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('ID', 'Id'), ('GROUP', 'Group'), ('NAME', 'Name'), ('CLASS', 'Class')], max_length=5)),
            ],
            options={
                'verbose_name': 'DOT lookup',
                'verbose_name_plural': 'DOT lookups',
                'ordering': ['value_type', 'value'],
            },
        ),
        migrations.CreateModel(
            name='WasteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code_type', models.CharField(choices=[('ST', 'State'), ('FD', 'Federal')], max_length=2)),
                ('state_id', models.CharField(blank=True, choices=[('AK', 'Alaska'), ('AL', 'Alabama'), ('AP', 'Armed Forces Pacific'), ('AR', 'Arkansas'), ('AZ', 'Arizona'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('IA', 'Iowa'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('ME', 'Maine'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MS', 'Mississippi'), ('MT', 'Montana'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NE', 'Nebraska'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NV', 'Nevada'), ('NY', 'New York'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VA', 'Virginia'), ('VI', 'Virgin Islands'), ('VT', 'Vermont'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming')], max_length=3, null=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WasteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(verbose_name='waste line number')),
                ('dot_hazardous', models.BooleanField(verbose_name='DOT hazardous')),
                ('dot_info', models.JSONField(blank=True, null=True, verbose_name='DOT information')),
                ('quantity', models.JSONField(blank=True, null=True)),
                ('hazardous_waste', models.JSONField(blank=True, null=True)),
                ('br', models.BooleanField(verbose_name='BR info provided')),
                ('br_info', models.JSONField(blank=True, null=True, verbose_name='BR information')),
                ('management_method', models.JSONField(blank=True, null=True, verbose_name='management method code')),
                ('pcb', models.BooleanField(verbose_name='contains PCBs')),
                ('pcb_infos', models.JSONField(blank=True, null=True, verbose_name='PCB information')),
                ('discrepancy_info', models.JSONField(blank=True, null=True, verbose_name='discrepancy-residue information')),
                ('epa_waste', models.BooleanField(verbose_name='EPA waste')),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='manifest.manifest')),
            ],
            options={
                'ordering': ['manifest__mtn', 'line_number'],
                'unique_together': {('manifest', 'line_number')},
            },
        ),
    ]
