name: 'Build Docker Image'
# This custom, reusable workflow builds and pushes a Docker image to GitHub Container Registry.

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
        description: 'The context to use for the Docker build.'
      image_name:
        required: true
        type: string
        description: 'The name of the image to build.'

jobs:
  build_image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.context }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Image Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
