name: Greetings

on: [ pull_request, issues ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hi, welcome to Haztrak!

            It looks like this is your first issue,
            If you're looking to contribute, be sure to check out our [contribution guideline](https://github.com/USEPA/haztrak/blob/main/docs/CONTRIBUTING.md),
            our [code of conduct](https://github.com/USEPA/haztrak/blob/main/docs/CODE_OF_CONDUCT.md)

            If you have have a question, the question may have been asked before and you can look at our [previous issues](https://github.com/USEPA/haztrak/issues?q=is%3Aissue+is%3Aclosed).
            You may also find the answer in our [documentation](https://github.com/USEPA/haztrak/tree/main/docs).

            Thanks!
          pr-message: |
            Thank you for your first Pull Request!
            If you're submitting a fix or a new feature, please ensure that you've also implemented tests so we know it's working.

            Thanks again
