name: Github Pages

on:
  push:
    branches:
      - main
  pull_request:
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/haztrak_book
    steps:

      - name: Setup
        uses: actions/checkout@v2

      - name: Setup mdBook
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.25/mdbook-v0.4.25-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin

      - name: inspect
        run: tree -L 2

      - name: Build Documentation
        run: bin/mdbook build

      - name: inspect
        run: tree -L 2

      - name: upload Docs
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/haztrak_book/book

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
