name: 'Create Release'
# This workflow runs when we create a release. It uses a custom reusable action to
# build our docker images and push them to the GitHub Container Registry.
# Before building images we run the unit tests to double-check that the images are working.

on:
  release:
    types: [published]

jobs:
  test_server:
    uses: ./.github/workflows/test_server.yaml

  test_client:
    uses: ./.github/workflows/test_client.yaml

  build_server:
    needs: [test_server]
    uses: ./.github/workflows/build_image.yaml
    with:
      context: ./server
      image_name: haztrak-server

  build_client:
    needs: [test_client]
    uses: ./.github/workflows/build_image.yaml
    with:
      context: ./client
      image_name: haztrak-client
