on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test_server:
    uses: ./.github/workflows/test_server.yaml

  test_client:
    uses: ./.github/workflows/test_client.yaml

  build_server:
    needs: [test_server]
    uses: ./.github/workflows/build_server.yaml

  build_client:
    needs: [test_client]
    uses: ./.github/workflows/build_client.yaml

  create_release:
    needs: [build_server, build_client]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
