name: 'Terraform lint'
# This workflow is responsible for running the Haztrak react client tests.

on:
  push:

jobs:
  check_terraform_fmt:
    name: 'Terraform Format'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/gcp
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'install terraform'
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common

      - name: 'install hashicorp GPG key'
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

      - name: 'add hashicorp repo'
        run: |
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
          https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
          tee /etc/apt/sources.list.d/hashicorp.list

      - name: 'update'
        run: apt update

      - name: 'install terraform'
        run: apt-get install terraform
