# Generated by Django 5.0.7 on 2024-07-22 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orgsite", "0002_alter_siteaccess_options_sitegroupobjectpermission_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitegroupobjectpermission",
            options={"verbose_name": "Site Role", "verbose_name_plural": "Site Roles"},
        ),
        migrations.AlterModelOptions(
            name="siteuserobjectpermission",
            options={"verbose_name": "Site Permission", "verbose_name_plural": "Site Permissions"},
        ),
    ]
